import { toast } from 'sonner';

// Mock AI functions for demonstration purposes
// In a real implementation, these would call actual AI APIs

export const generateDocument = async (params) => {
  const { topic, pages, tone, type } = params;
  
  // Simulate API call delay
  await new Promise(resolve => setTimeout(resolve, 1500));
  
  const mockContent = `
# ${topic}

This is a ${tone.toLowerCase()} ${type.toLowerCase()} about ${topic}. It spans approximately ${pages} page(s).

## Introduction

Artificial intelligence and machine learning have revolutionized the way we approach problem-solving in the modern world. This document explores the various aspects of ${topic} and provides insights into its applications.

## Main Content

The main body of this document would contain detailed information about ${topic}. We would typically include multiple sections with headings, subheadings, and supporting content.

## Conclusion

In conclusion, ${topic} represents an important area of study and application in today's technology-driven landscape. Further research and development in this field will likely yield even more impressive results.

---

Generated by AI Assistant
  `;
  
  return mockContent;
};

export const rewriteText = async (text) => {
  await new Promise(resolve => setTimeout(resolve, 800));
  return `Rewritten version: ${text}`;
};

export const expandText = async (text) => {
  await new Promise(resolve => setTimeout(resolve, 800));
  return `${text} This is an expanded version with additional content to provide more detail and context to the reader.`;
};

export const summarizeText = async (text) => {
  await new Promise(resolve => setTimeout(resolve, 800));
  return `Summary: This is a brief summary of the original text which was about "${text.substring(0, 20)}...".`;
};

export const changeTone = async (text, tone = 'professional') => {
  await new Promise(resolve => setTimeout(resolve, 800));
  return `[${tone} tone] ${text}`;
};

export const fixGrammar = async (text) => {
  await new Promise(resolve => setTimeout(resolve, 800));
  return `Grammar corrected: ${text}`;
};

export const bulletToParagraph = async (text) => {
  await new Promise(resolve => setTimeout(resolve, 800));
  return `Converted bullets to paragraph format: ${text}`;
};

export const generateCode = async (description, language = 'javascript') => {
  await new Promise(resolve => setTimeout(resolve, 1000));
  
  const codeSnippets = {
    javascript: `// JavaScript code for: ${description}
function exampleFunction() {
  console.log("Hello, World!");
  return true;
}`,
    python: `# Python code for: ${description}
def example_function():
    print("Hello, World!")
    return True`,
    java: `// Java code for: ${description}
public class Example {
    public static void main(String[] args) {
        System.out.println("Hello, World!");
    }
}`,
    html: `<!-- HTML for: ${description} -->
<!DOCTYPE html>
<html>
<head>
    <title>Example</title>
</head>
<body>
    <h1>Hello, World!</h1>
</body>
</html>`
  };
  
  return codeSnippets[language] || codeSnippets.javascript;
};

export const explainCode = async (code, language = 'javascript') => {
  await new Promise(resolve => setTimeout(resolve, 1000));
  return `Explanation of the ${language} code:\n\nThis code snippet demonstrates a basic example that prints "Hello, World!" to the console.`;
};

export const refactorCode = async (code, language = 'javascript') => {
  await new Promise(resolve => setTimeout(resolve, 1000));
  return `// Refactored ${language} code:\n${code}\n\n// Optimized for better performance and readability.`;
};

export const addComments = async (code, language = 'javascript') => {
  await new Promise(resolve => setTimeout(resolve, 1000));
  return `// Added comments to ${language} code:\n// This is the beginning of the code\n${code}\n// End of code with comments`;
};